#==============================================================================
# .zprofile - last update 20140207
#==============================================================================
# Executes commands at login pre-zshrc.

#------------------------------------------------------------------
# Editors
#------------------------------------------------------------------
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#------------------------------------------------------------------
# Language
#------------------------------------------------------------------
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#------------------------------------------------------------------
# Paths
#------------------------------------------------------------------
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $HOME/.local/{bin,sbin}
  $path
)

#------------------------------------------------------------------
# Less
#------------------------------------------------------------------
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#------------------------------------------------------------------
# Temporary Files
#------------------------------------------------------------------
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

#------------------------------------------------------------------
# Linux logo
#------------------------------------------------------------------
if [[ -o login ]]; then
    [ -x /usr/bin/linux_logo ] && { echo; linux_logo -a -c -d -f -k -u -y;}
fi

#------------------------------------------------------------------
# User specific environment and startup programs
#------------------------------------------------------------------
export http_proxy='http://direct.proxy.i2:8080'
export https_proxy='http://direct.proxy.i2:8080'
export ftp_proxy='ftp://direct.proxy.i2'

#------------------------------------------------------------------
# Defragmentation des bases sqlite de Firefox
#------------------------------------------------------------------
# for f in ~/.mozilla/firefox/*/*.sqlite; do sqlite3 $f "VACUUM;" 2>/dev/null; done

#------------------------------------------------------------------
# Vagrant
#------------------------------------------------------------------
export VAGRANT_HOME='/mnt/phildoc/informatique/boxes/vagrant/'
